### ISSUE TITLE
[BUG]: Flasbax bug on LBF (type issue)

### ISSUE THREAD

**Issue by lbeyers** [instadeepai/Mava#1032]
### Describe the bug
In the AgentID wrapper, the new_agents_view type is not enforced to be consistent, so for LBF with flashbax a dtype error emerges.

### To Reproduce
1. Run LBF with flashbax.

### Expected behavior
Expected the observation to be added easily to the buffer.

### Context (Environment)
 - Updated jumanji

### Additional context
This is somewhat an exercise in opening an issue!

### Possible Solution
Will make a PR soon! Basically a cast to the agents_view type.

**Comment by WiemKhlifi** [comment]
Thank you @lbeyers for catching this! 
A question here, did you test this with Rware? And can you please test this with Matrax as well 🙏 

Extra: This [commit](https://github.com/instadeepai/Mava/commit/4aad61dba580ab6a33ccfe17716fa5dbe6d892ab) would help for understanding the issue at the moment 😄
