### ISSUE TITLE
[FEATURE] Set time limit per scenario

### ISSUE THREAD

**Issue by SimonDuToit** [instadeepai/Mava#1060]
Currently the time limit, along with other `kwargs`, are set in the environment config and cannot be specified for individual scenarios. This is a problem as for some environments (e.g. cleaner) a larger scenario may require significantly more timesteps to solve. There should be a way to specify the time limit in individual scenarios. The simplest way to change this is simply moving `kwargs` to the scenario config and repeating arguments that are the same across scenarios, but we could also treat time limit separately to other `kwargs` if we know that every environment has it.

**Comment by sash-a** [comment]
Fixed by #1068
