### ISSUE TITLE
[BUG] Quickstart Colab imports failing

### ISSUE THREAD

**Issue by Brunozml** [instadeepai/Mava#1074]
### Describe the bug
Running the Quickstart notebook fails to install the necessary dependencies, resulting in failed imports. `GlobalStateWrapper`,  `LearnerState`, and `evaluator_setup` seem to be the problems, but `AgentIDWrapper` and `RecordEpisodeMetrics ` imports do work.

### To Reproduce
```
27 from mava.wrappers.jumanji import RwareWrapper
---> 28 from mava.wrappers import AgentIDWrapper, GlobalStateWrapper, RecordEpisodeMetrics
     29 from mava.types import (
     30     ActorApply,

ImportError: cannot import name 'GlobalStateWrapper' from 'mava.wrappers' (/usr/local/lib/python3.10/dist-packages/mava/wrappers/__init__.py)
```
and same for ```from mava.types import (
    ActorApply,
    CriticApply,
    ExperimentOutput,
    LearnerFn,
    LearnerState,
    Observation,
    ObservationGlobalState,
    OptStates,
    Params,
    PPOTransition,
)```
```
ImportError: cannot import name 'LearnerState' from 'mava.types' (/usr/local/lib/python3.10/dist-packages/mava/types.py)
```
and `from mava.evaluator import evaluator_setup`: 
```
ImportError: cannot import name 'evaluator_setup' from 'mava.evaluator' (/usr/local/lib/python3.10/dist-packages/mava/evaluator.py)

```

### Expected behavior
imports occur without an issue.

**Comment by RuanJohn** [comment]
Hey @Brunozml, thank you for the issue. We will get on fixing this as soon as possible and will let you know once it is sorted!

**Comment by RuanJohn** [comment]
Hey @Brunozml, the quickstart notebook should run fine now. Please let us know if you face any other issues :)
