### ISSUE TITLE
[BUG] ModuleNotFoundError in Colab Quickstart Notebook

### ISSUE THREAD

**Issue by riverliway** [instadeepai/Mava#1117]
### Describe the bug
Running the Google Colab Quickstart Notebook provided cell by cell results in a `ModuleNotFoundError` on running the 3rd cell. This notebook was working a few weeks ago.

### To Reproduce
1. Open https://colab.research.google.com/github/instadeepai/Mava/blob/develop/examples/Quickstart.ipynb
2. Start a new session connected to a GPU backend
3. Run the first cell "Install Mava"
4. Run the second cell "Restart Google Colab runtime"
5. Run the third cell "Import required packages."
6. Observe the python error

### Expected behavior
The quickstart notebook executes as expected

### Context (Environment)
 - Colab

### Additional context
![image](https://github.com/user-attachments/assets/df0c7c60-f480-4a12-9c0c-7213c89c3d6e)

### Possible Solution
I tried just adding pip install of the packages that were throwing the errors, but then it gave me a ModuleNotFound error for Mava.

**Comment by RuanJohn** [comment]
Hi @riverliway, 

Thank you for bringing this up and for the detailed description! We are currently restructuring the repo a bit which is why I think the imports are failing. 

We'll fix it soon!
