### ISSUE TITLE
Custom environment

### ISSUE THREAD

**Issue by Ueshima73** [instadeepai/Mava#1133]
Thank you for the great repository! I was wondering if there is a tutorial on how to add a custom environment. 

I would like to create a new environment and found the file [mava/types.py](https://github.com/instadeepai/Mava/blob/6092dc656cd73ee5a0fb0dd6e29c50b11c9b84ac/mava/types.py#L36), which points to [mava/wrappers/jumanji.py](https://github.com/instadeepai/Mava/blob/develop/mava/wrappers/jumanji.py). Although I could confirm that the file contains the JumanjiMarlWrapper class, I’m still unsure how to get started.

Thanks!

**Comment by sash-a** [comment]
Hi @Ueshima73 unfortunately we don't have any tutorials on creating a custom environment. If you'd like to create one maybe having a look at some of the many environments in [jumanji](https://github.com/instadeepai/jumanji) and starting from one of those?

Everything in the `mava/wrappers` folder is used to make environments from different libraries work in mava, they are not the environment implementations but rather simple wrappers to transform their API to what mava expects.

What type of environment do you want to make? Maybe I can point you in the right direction :smile:

**Comment by Ueshima73** [comment]
Thanks, @sash-a for the prompt response!

Yes, I am checking the Jumanji codebase. It looks very helpful.

> Everything in the mava/wrappers folder is used to make environments from different libraries work in MAVA. They are not the environment implementations, but rather simple wrappers to transform their API into what MAVA expects.

OK, so am I correct in assuming that it is possible to create a native MAVA environment that doesn't need to be wrapped? In that case, I wonder if I need not to start with a Jumanji-style environment, as suggested in `mava/types.py`? I wonder the reason It says 
> A mava environment simply uses the Jumanji env API with a few added attributes.
>     For examples of how to add custom environments to Mava see `mava/wrappers/jumanji.py`.
>     Jumanji API docs: https://instadeepai.github.io/jumanji/#basic-usage

> What type of environment do you want to make? Maybe I can point you in the right direction 😄

Thanks for the kind word! I would like to create a very simple Prisoner's Dilemma environment, a 2 * 2 matrix game in which two agents each can select cooperate or defect. The script itself should be very simple, but I think I am still unsure what MAVA expects.

**Comment by sash-a** [comment]
Yes you definitely can make one that doesn't need to be wrapped. In your jumanji env just define [three extra attributes](https://github.com/instadeepai/Mava/blob/develop/mava/types.py#L41-L43): 
```python
    num_agents: int
    time_limit: int
    action_dim: int
```

The rest of the env api comes from jumanji, so if you make a jumanji env with the correct specs and methods it should just work.

Apologies I guess those docs are a bit misleading - that's examples of how to wrap a custom env that you've already made.

That should be very simple, you can have a look at [matrax](https://github.com/instadeepai/matrax) for our implementation of multi-agent matrix games

If you need any help feel free to reach out :smile:

**Comment by Ueshima73** [comment]
Thank you so much, @sash-a! Everything about the wrapping is clear to me now. No worries about the documentation, of course.

I will definitely check out matrax! It looks pretty helpful.

I look forward to mentioning Mava in my publication in the future.

**Comment by sash-a** [comment]
Pleasure, hope the env is easy to make and mava works well! A last thing I forgot to mention @Ueshima73 make sure that your observation type is the same as [Mava's](https://github.com/instadeepai/Mava/blob/develop/mava/types.py#L110), it needs to have these 3 attributes because our networks/algorithms expect the following attributes within an observation:

```python
    agents_view: chex.Array  # (num_agents, num_obs_features)
    action_mask: chex.Array  # (num_agents, num_actions)
    step_count: chex.Array  # (num_agents, )
```

If you're going to do centralized training (e.g mappo) then you also need to add `global_state` to this, see [here](https://github.com/instadeepai/Mava/blob/develop/mava/types.py#L123).
