### ISSUE TITLE
[MAINTAIN] Review of Mava vs JaxMARL SMAX Results

### ISSUE THREAD

**Issue by amacrutherford** [instadeepai/Mava#1149]
### Please describe what needs to be maintained?
Hey folks, hope all is well! would you mind taking another look at the JaxMARL vs Mava SMAX results outlined in your readme [here](https://github.com/instadeepai/Mava?tab=readme-ov-file#smax) as they are out of date if you look at the current arxiv version of JaxMARL.

### Describe the outcome you'd like
Graphs updated to reflect the correct final win rates achieved by JaxMARL

### How do we know when maintenance is complete?
Checklist:
- [ ] Graphs updated

**Comment by RuanJohn** [comment]
Hey @amacrutherford, thanks for bringing to our attention! We are actually in the process of doing a full readme update and will not have the JaxMARL comparison anymore. Please have a look [here](https://github.com/instadeepai/Mava/tree/feat/readme-revamp) to see what the new readme will look like.
