### ISSUE TITLE
Mava/examples/quickstart.ipynb debug environment trained but did not generate recording .HTML files

### ISSUE THREAD

**Issue by mnguyen0226** [instadeepai/Mava#280]
Hi,
Thank you for making this framework publicly. I am currently exploring the framework and play around with some of the examples you provided. I was able to train and see results on Tensorboard with the "MAVA Quickstart Notebook" you provided. However, I was not able to see any .HTML files from the "recording directory".

For your information, I used "main" branch, run on Linux Ubuntu, I copy section 1-3 of the Quickstart notebook to .py script and run it via terminal instead of using Jupyter Notebook. I was able to see the debug environment render and run until it fail during the training process. I acknowledge that the code section that used for recording is this 

![image](https://user-images.githubusercontent.com/56325621/127012502-84fc9ea4-786c-44ba-87dc-71bff33a0c14.png)

Here is the result from tensorboard.

![image](https://user-images.githubusercontent.com/56325621/127011342-7413663d-4def-44c9-9254-52a0d189652d.png)

It is stated in the notebook that "A good score is a RawEpisodeReturn between 30-40. Although this system is stochastic, it should reach that score atleast by 100 evaluator episodes. Once a good score is reached, you can view intelligent multi-agent behaviour by viewing the agent recordings." I have changed "record_every" param to 10 instead of default 100

Here is the checkpoints/ I got: 

![image](https://user-images.githubusercontent.com/56325621/127011873-12a5401d-8856-4641-91fa-02b6218e1c7c.png)

However there is no .HTML generated even when I got more than 40 for RawEpisodeReturn 

![image](https://user-images.githubusercontent.com/56325621/127012122-410e77be-c517-4f3b-919c-329eb5708899.png)

**Updates:**
I switch to save on .gif and it seems to provide .gif files. However, they are empty. I doubt that for some reason, the code in Mava/wrappers/environment_loop_wrappers/MonitorParallelEnvironmentLoop > _append_frame did not add frame to frames[] list. I tried to open manually and via opencv the .gif files but no luck.

![image](https://user-images.githubusercontent.com/56325621/127054976-04aebc14-53a7-4718-bc10-caa376d4861b.png)

**WIll you please let me know why this is the case?**

**Comment by KaleabTessera** [comment]
Hi @mnguyen0226 , thanks for submitting this issue! 

So what is likely happening is that you haven't setup a virtual display, which is required to record the agents acting in the environment. 

Firstly, I would recommend viewing the logs (`cat /tmp/launchpad_out/evaluator/0` or remove the `terminal="output_to_files",` resulting in the logs printing to screen) , this should give you more information as to the exact error. 

We have setup the virtual display in the dockerfile and in the notebook (see the second cell under installation). If the notebook installation for a virtual display fails, please follow step 4 from the [Optional Install doc](https://github.com/instadeepai/Mava/blob/develop/OPTIONAL_INSTALL.md).

**Comment by mnguyen0226** [comment]
Hi @KaleabTessera ,
---------------------------- About format = "video":
Thank you for your suggestion! For some reason, I was not able to view log (cat /tmp/launchpad_out/evaluator/0) that you mentioned but able to use the optional install doc - 4/ with this **xvfb-run -a python [script.py]**

This allow me to record .html videos for Debug Env and MultiWalker: 
![image](https://user-images.githubusercontent.com/56325621/127199869-4c1a945b-bd38-44b8-8056-fd3cfef27363.png).

However, **this is not applicable for SMAC's .**html video although the examples script  is running and Tensorboard training is just fine.  The Debug Env and MultiWalker environments are recorded as I expected since I was able to see the rendering screen popped up (not the save .HTML) during the training process. I was not able to render SMAC on Linux.

=> I highly doubt that it's a certain correct way to install SMAC on Linux and get it to render. Will you please provide steps on how you install SMAC on Linux and get it to render?

---------------------------- About format = "gif":
I tested the same command **xvfb-run -a python [script.py]** on Multi-walker and Debug environment with the format gif. However I still get the same error that "GIF Image is truncated or corrupted" as above.

I see that in the Optional Install doc there is this:
![image](https://user-images.githubusercontent.com/56325621/127200719-d7bd04fd-d84d-465b-82bf-055ccd2cc5a1.png)

I'm not entirely sure what this mean, is this for converting .html or .gif since .[record_episode] is not a package.

Thanks!

**Comment by KaleabTessera** [comment]
Congrats on being able to record html for Debug and MuliWalker! 

## Error Message
For SMAC, do you see any errors on the terminal? If you are logging to the terminal (in lp.launch you have ` terminal="current_terminal`), it should show you errors if something relating to the recording has failed. 

## Install Smac Linux 
Our recommended way to run most systems is through docker, because most configurations are different and it is difficult to handle all the variants. For installing smac, please try the following:
```
pip install pysc2
pip install git+https://github.com/oxwhirl/smac.git
```
Then install  multi-agent Starcraft 2 environment : 
```
 ./install_sc2.sh
```
Then set `SC2PATH` to the location of 3rdparty/StarCraftII, e.g. : 
```
export SC2PATH="/Code/Mava/3rdparty/StarCraftII"
```
For issues with this installation, also possibly check the [smac repo](https://github.com/oxwhirl/smac). 

## Gif Format 
For the gif format, we use `array2gif`. If you run `pip install .[record_episode]` it will install `array2gif` (look in our setup.py). 

## Next Steps
Do you have a specific, reproducible example/code snippet that you are running? Also please send me the output of `pip list` and any error message you see on the screen during recording.

**Comment by mnguyen0226** [comment]
Hi @KaleabTessera,

## SMAC
Thank you for your suggestion. For Debugging Env, Multiwalker, and SMAC I have tried with conda virtual environment and was able to render and save .html for debugging and multiwalker but not for SMAC. For now, I just try to reproduce your examples on my Linux with some minor change in saving variables. For all of the env, I have tried both terminal="current_terminal" and "out-to-files" and they both are helpful in debugging.

I have tried to reproduce SMAC via virtual conda env for couple days and I was not surprise that it was not work since there might be some variables that I did not install properly. The original SMAC+PyMARL suggest Linux user to trained on Linux and render on Windows but the code for both repos have not been updated for a while and I have hard time debugging them both.

## DOCKER
 I end up tried with DOCKER that you suggested and got it to work (train, render and save) for SMAC (but not for Debug and Multiwalker - however this is fine since the two env works on virtual conda env instead of using Docker).

![image](https://user-images.githubusercontent.com/56325621/127413252-6caf4abd-ba33-43c8-961f-e37392dc7c82.png)


## ERROR

## GIF
