### ISSUE TITLE
How to render SMAC on Linux?

### ISSUE THREAD

**Issue by mnguyen0226** [instadeepai/Mava#282]
Thank you for providing the examples script for SMAC. There has been a lot of problem in rendering SMAC via Linux and it seems like the way that the author on SMAC suggested to do is to trained agent on PyMARL then save and render on Window or Wine for linux. 

I installed both SMAC and pysc2 on my linux and was able to run PySC2 example "python -m pysc2.bin.agent --map Simple64" with rendering screen but **not** for SMAC example "python -m smac.examples.random_agents".

I was able to run your SMAC's 2 examples scripts and saw their improvement via Tensorboard. However, there is no rendering screen. 

I acknowledge that Mava use Launchpad for distribution process which is available only for Linux for now. W**ill you provide steps on how to provide this .gif/.HTML or render on Linux?**

Here is the .gif/.HTML I mentioned: https://github.com/instadeepai/Mava/blob/develop/docs/images/sc2_animation.gif

Thank you

**Comment by KaleabTessera** [comment]
Hi @mnguyen0226 , seems like a similiar issue to https://github.com/instadeepai/Mava/issues/280 . Please follow step 4 from the [Optional Install doc](https://github.com/instadeepai/Mava/blob/develop/OPTIONAL_INSTALL.md), in Ubuntu (or Linux based systems) this should allow you to record agents acting in the environment. 

Please let us know if you still have issues after the install.

**Comment by KaleabTessera** [comment]
Closing and continuing the discussion in issue https://github.com/instadeepai/Mava/issues/280 .
