### ISSUE TITLE
Typo on simple_spread debugging env

### ISSUE THREAD

**Issue by mlanas** [instadeepai/Mava#287]
Hi,
I was playing around with the simple_spread debugging environment and found a typo in the observation function, specifically in the landmark distance calculation. Instead of subtracting the agent position the same landmark position is being subtracted resulting on the last 4 values of the observation vector always being zero.

https://github.com/instadeepai/Mava/blob/e6d0ea8d0b1e7e02d19f2cc89446948d8de74888/mava/utils/debugging/scenarios/simple_spread.py#L113

**Comment by arnupretorius** [comment]
Hi @mlanas, thanks for spotting this! 🤗  

We will look into it.

**Comment by DriesSmit** [comment]
Good catch @mlanas ! :fire: I will create a PR correcting this. Just make sure that you agree with the changes :+1:

**Comment by mlanas** [comment]
Thanks @DriesSmit ! The fix looks good and the code is much more clear now. :+1:
