### ISSUE TITLE
Evaluating model after training is done?

### ISSUE THREAD

**Issue by mlanas** [instadeepai/Mava#289]
**Is there an easy way in Mava to load a trained model from the checkpoints, run it again and evaluate it's performance?**

I haven't found any example on how to do this and can't find and easy way to do it just by looking at the code.
- Is this already implemented in Mava?
- If not, could you please point out a way for me to implement this?

To make it more clear, the reason I need this is because I'm working with a model topology that allows a variable number of agents as input. This means I can train the model using a 3-agent environment, but after the training is done I can use this trained model and run it on the same environment with more or less agents and I want to evaluate the performance with different number of agents.

**Comment by DriesSmit** [comment]
Hello @mlanas. Mava has built-in checkpointing available if you set `checkpoint` to true in the system config.  Therefore the networks are automatically checkpointed throughout training. When starting a run again the checkpointer will look in the provided director (`checkpoint_subpath`) to try and restore the networks. I am actually also working on an environment with a variable number of agents as input because the observation space is number_of_agents agnostic. And I have confirmed that checkpointing does work in this case. Just make sure that in your evaluation run the checkpointer is look at the correct folder. I normally check if the sum of network weights has changed after the checkpointer to confirm that I actually loaded the trained weights correctly. Also if you are using Docker just make sure that you are saving to a mounted volume. Let me know if you are still having problems?

**Comment by mlanas** [comment]
Thanks for the answer @DriesSmit . Okay but that means that I have to create a whole system again, this will restore this checkpoint and continue the training right? What if I don't want to continue training? I just want to run the restored model in an environment, save the recordings and see the statistics. Is this possible by setting some system config? Or is it maybe possible to only run an Evaluator?

And about that number_of_agents agnostic observation space, are you talking about a new environment? or is this like a wrapper for Mava environments?

**Comment by DriesSmit** [comment]
At the moment this does require a bit of extra code to run a system just for evaluation. I do this by just creating the program, but not launch it. After that, you can load the networks manually and work with the policy network directly. But this is not ideal. Our new [multiple trainer system](https://github.com/instadeepai/Mava/tree/feature/mava-scaling) should be able to do exactly what you want, however, it is still experimental and a [PR](#253) is out for it. There you can set the `num_executors=0` and `trainer_networks={}`. This should create a run with only the variable server and one evaluator running. This new Mava version has a centralised variable server and does not use the trainer as the variable server anymore. If something does break I am happy to fix it.  The evaluator then gets the networks directly from the variable server. This branch also allows you to launch multiple trainers if needed. Just note that this code might still change quite a bit as the PR gets reviewed.

For `number_of_agents` agnostic observation space I mean that if the agent's observation size does not change w.r.t. the number of agents then it should be fine. The variable server only loads the networks. So you can run the trained networks on any environment with any number of agents, as long as the inputs (observations) and outputs (actions) of the networks remain the same.

**Comment by DriesSmit** [comment]
@mlanas Did I answer your questions? Or would you like some more clarification?

**Comment by mlanas** [comment]
@DriesSmit sorry for the late response. I wanted to use the multiple trainer system as you mentioned, last days I've been taking a look at that, but I found some issues with the training on that branch. I need a more stable and faster solution, so I thought of using the mava version on pip and implement this evaluation myself as you mentioned. Although this is not ideal, it should do the trick right? can you help me with this? So you say I need to create the program (and build it?) but not launch it. Then how exactly do I load the networks and then should I only execute the Evaluator?

**Comment by DriesSmit** [comment]
Thanks for the reply @mlanas. I can definitely try and help you using the pip mava version. I might have found an easy way to solve your problem. Just a quick question. What did not work for you on the multiple trainer branch? It would be great if it is something I can fix. I have gone over the code and I think there might be an easy way to only run the evaluator without training. Firstly set `num_exectors=0` in the system config. If there is an error with this setting I can gladly help and fix it. Then also set the `trainer_fn` to the trainer you used to train the system with. The only thing that is left to do is to wrap this 'trainer_fn', before sending it to the system, with a custom wrapper that overwrites the run function of the trainer. The run function can just be replaced with something like `time.sleep(9999999)`. This will therefore still create the complete system with a trainer that loads the variables and then run the evaluator. When it tries to run the trainer is will just sleep and not update anything.

**Comment by mlanas** [comment]
I tried wrapping the class like this:
```python
class EvaluationTrainer(maddpg.MADDPGDecentralisedTrainer):
    def run(self, **kwargs):
        time.sleep(9999999)
```
```python
program = maddpg.MADDPG(
        environment_factory=environment_factory,
        network_factory=network_factory,
        logger_factory=logger_factory,
        num_executors=0,
        policy_optimizer=snt.optimizers.Adam(learning_rate=1e-4),
        critic_optimizer=snt.optimizers.Adam(learning_rate=1e-4),
        checkpoint_subpath=checkpoint_dir,
        max_gradient_norm=40.0,
        trainer_fn=EvaluationTrainer,
        eval_loop_fn=MonitorParallelEnvironmentLoop,
        eval_loop_fn_kwargs={"path": checkpoint_dir, "record_every": 100},
    ).build()
```

But I'm getting this error:
```bash
[trainer/0] Traceback (most recent call last):
[trainer/0]   File "/home/manuel/Mava/.venv/lib/python3.8/site-packages/launchpad/nodes/python/process_entry.py", line 92, in <module>
[trainer/0]     app.run(main)
[trainer/0]   File "/home/manuel/Mava/.venv/lib/python3.8/site-packages/absl/app.py", line 312, in run
[trainer/0]     _run_main(main, args)
[trainer/0]   File "/home/manuel/Mava/.venv/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
[trainer/0]     sys.exit(main(argv))
[trainer/0]   File "/home/manuel/Mava/.venv/lib/python3.8/site-packages/launchpad/nodes/python/process_entry.py", line 87, in main
[trainer/0]     functions[task_id]()
[trainer/0]   File "/home/manuel/Mava/.venv/lib/python3.8/site-packages/launchpad/nodes/python/node.py", line 72, in _construct_function
[trainer/0]     return functools.partial(self._function, *args, **kwargs)()
[trainer/0]   File "/home/manuel/Mava/.venv/lib/python3.8/site-packages/launchpad/nodes/courier/node.py", line 107, in run
[trainer/0]     instance = self._construct_instance()  # pytype:disable=wrong-arg-types
[trainer/0]   File "/home/manuel/Mava/.venv/lib/python3.8/site-packages/launchpad/nodes/python/node.py", line 165, in _construct_instance
[trainer/0]     return self._constructor(*args, **kwargs)
[trainer/0]   File "/home/manuel/Mava/.venv/lib/python3.8/site-packages/mava/systems/tf/maddpg/system.py", line 354, in trainer
[trainer/0]     return self._builder.make_trainer(
[trainer/0]   File "/home/manuel/Mava/.venv/lib/python3.8/site-packages/mava/systems/tf/maddpg/builder.py", line 410, in make_trainer
[trainer/0]     trainer = self._trainer_fn(**trainer_config)
[trainer/0]   File "/usr/lib/python3.8/typing.py", line 875, in __new__
[trainer/0]     obj = super().__new__(cls, *args, **kwds)
[trainer/0] TypeError: object.__new__() takes exactly one argument (the type to instantiate)
```

So I modified the function inside Mava for now and it does work, just the evaluator runs. But I'm not seeing any new recordings in the log folder and this is what I see in the tensorboard log:

![image](https://user-images.githubusercontent.com/56938299/129218358-0f25ce18-cae9-44bc-aa1d-4014d442ad12.png)

Orange was my training and green is the evaluation I'm running now. It seems like I'm running a new randomly initialized model. I think my checkpoint path is set correctly, but I'll take a deeper look into that.

**Comment by DriesSmit** [comment]
Yes, it seems that for some reason the checkpointer did not load the model parameters. My best guess is because in your main code you probably still have this flag:

`flags.DEFINE_string(
    "mava_id",
    str(datetime.now()),
    "Experiment identifier that can be used to continue experiments.",`
This flag basically specifies the subdirectory to create and store your checkpoint and tensorboard logs in. In its current form, it uses the current datetime to create a new subdirectory. If you want to load an already trained example just replace `str(datetime.now())` with the name (datetime) of the subfolder your already trained example is in. I hope this works for you?
Maybe the episode recorder is recording to the newly created subfolder as well?

**Comment by mlanas** [comment]
I did modify the flag and is not working. I'm testing now with the debugging env example [run_maddpg.py](https://github.com/instadeepai/Mava/blob/0a952cc124dcb5e9a00250ba7a6e8eab57ea25d2/examples/debugging/simple_spread/feedforward/decentralised/run_maddpg.py). I just modified the ```mava_id``` flag to "test_model" and the ```base_dir``` flag to "./logs". I run it once to train and the second time I run it I get a new plot in the tensorboard log:

![Screenshot from 2021-08-17 11-14-12](https://user-images.githubusercontent.com/56938299/129699119-d4aaf29d-ce51-4981-8b94-15f0609b37fb.png)

It is working on the same log folder but its training a new model from scratch.

I noticed that after the first run, the files with prefix "ckpt-1." are created in the checkpoints directory. But when I run it for the second time its attempting to restore "ckpt-2." (as you can see in the next log) which doesn't exist. When I check the folder after this second run there are no more "ckpt-1." files anymore, I can see "ckpt-2." instead.

```bash
[counter/0] I0817 11:14:44.158990 140585176217408 savers.py:165] Attempting to restore checkpoint: ./logs/test_model/checkpoints/counter/ckpt-2
[counter/0] I0817 11:14:44.162575 140585176217408 courier_utils.py:51] Binding: get_counts
[counter/0] I0817 11:14:44.162759 140585176217408 courier_utils.py:51] Binding: increment
[counter/0] I0817 11:14:44.162853 140585176217408 courier_utils.py:51] Binding: restore
[counter/0] I0817 11:14:44.162940 140585176217408 courier_utils.py:51] Binding: save
[counter/0] I0817 11:14:44.163712 140585176217408 savers.py:156] Saving checkpoint: ./logs/test_model/checkpoints/counter
```

Am I doing something wrong or is this a different issue?

**Comment by DriesSmit** [comment]
Are you using docker for your setup? What volume (`-v`) are you mounting? I usually mount `-v ${PWD}:/home`. If you are mounting home can you try setting the `base_dir` to `/home/logs/` instead?

  Maybe try something like this?

> flags.DEFINE_string(
    "mava_id",
    "test_model", #str(datetime.now()),
    "Experiment identifier that can be used to continue experiments.",
)
flags.DEFINE_string("base_dir", "/home/mava_logs/", "Base dir to store experiments.")

@jcformanek Is there anything else in the develop branch you need to do to actually load a model?

**Comment by DriesSmit** [comment]
Otherwise, if you can attach a stripped-down version of your code. Then I can take a look.

**Comment by mlanas** [comment]
My code is exactly the one in [run_maddpg.py](https://github.com/instadeepai/Mava/blob/0a952cc124dcb5e9a00250ba7a6e8eab57ea25d2/examples/debugging/simple_spread/feedforward/decentralised/run_maddpg.py) only changed those flags:
```python
flags.DEFINE_string(
    "mava_id",
    "test_model",
    "Experiment identifier that can be used to continue experiments.",
)
flags.DEFINE_string("base_dir", "./logs", "Base dir to store experiments.")
```

I'm not using docker here, just the pip version of mava installed in a virtual environment.

**Comment by DriesSmit** [comment]
I think I might know what the problem is. Currently, our checkpointer only saves once every 15 minutes. So maybe it did not run long enough to save yet in your case? I will update the code to make the checkpointer's save_interval configurable.

**Comment by mlanas** [comment]
Yees! That was the problem, now is working, thanks. Now I'll give a try to the ```num_exectors=0``` idea for evaluating the model. Just for me to know, why are there 2 folders in the checkpoint directory (counter and trainer)?? what's in those 2?

**Comment by DriesSmit** [comment]
The counter folder saves counter values such as step counts, episode counts etc for the evaluator, executor and trainers. In the trainer folder, the network weights get stored. P.S. in the new version of Mava (`feature/mava-scaling` branch) everything gets stored inside variable_server.

**Comment by mlanas** [comment]
It's working now, I managed to train a model once and evaluate it while varying the number of agents :smile: . Thank you @DriesSmit for your help!!

**Comment by DriesSmit** [comment]
Great! :smile: I am glad its working.
