### ISSUE TITLE
Training affected in development branches

### ISSUE THREAD

**Issue by mlanas** [instadeepai/Mava#294]
# Problem
[develop](https://github.com/instadeepai/Mava/tree/develop) and [feature/mava-scaling](https://github.com/instadeepai/Mava/tree/feature/mava-scaling) branches seem to be taking longer to train the debugging environment example [run_maddpg.py](https://github.com/instadeepai/Mava/blob/develop/examples/debugging/simple_spread/feedforward/decentralised/run_maddpg.py) than the [0.1.0](https://github.com/instadeepai/Mava/commit/80004d3e8950259c4290f11d77ff3d8fbcc40d61) release. The difference between _0.1.0_ and _develop_ is not that big, but the _feature/mava-scaling_ one does seem to affect the training considerably.

| 0.1.0 runs | develop runs   |      feature/mava-scaling runs      |
|:-------------:|:-------------------:|:-------------------------------------------:|
| ![0 1 0_runs](https://user-images.githubusercontent.com/56938299/129061460-8c0251b0-eac9-499a-be6c-f20715edf9b3.png) | ![develop_runs](https://user-images.githubusercontent.com/56938299/129057900-fc81aee0-dcb1-47c4-98e6-85512b5602b6.png) |  ![scaling_runs](https://user-images.githubusercontent.com/56938299/129057942-bf698c16-f08b-49be-a79a-6ab05f5d0ca9.png) |

# Execution
The tests were executed using docker. Each branch was cloned to a different directory and the 3 docker images were built.

For each branch, the test was executed 3 times with the command:
```bash
make run-tensorboard
```

# Note
After cloning the 0.1.0 tag, the [simple_spread.py](https://github.com/instadeepai/Mava/blob/develop/mava/utils/debugging/scenarios/simple_spread.py) file of the debugging environment was updated to incorporate the changes added in #288 so all the tests are executed in the same environment.

**Comment by DriesSmit** [comment]
Wow thanks for these results :smile: :fire:  This is definitely something I will be investigating today. Did you check the timestamps just to confirm that it was not something to do with the time per step that changed and that it did actually train longer?

**Comment by DriesSmit** [comment]
Also are you using a GPU in your experiments?

**Comment by mlanas** [comment]
I do have a GPU, but apparently I did not use it for the tests. When running the ```make run-tensorboard``` command I get this error:

```bash
docker run --gpus all -p 6006:6006 -it --rm  -v /home/manuel/mava_contribute/mava_scaling:/home/app/mava -w /home/app/mava mava:scaling /bin/bash -c "  tensorboard --bind_all --logdir  /home/app/mava/logs/ & python examples/debugging/simple_spread/feedforward/decentralised/run_maddpg.py --base_dir /home/app/mava/logs/; "
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
make: *** [Makefile:33: run-tensorboard] Error 125
```

So for the tests I ran that command using sudo and I dont see the gpus flag printed:

```bash
docker run  -p 6006:6006 -it --rm  -v /home/manuel/mava_contribute/mava_scaling:/home/app/mava -w /home/app/mava mava:scaling /bin/bash -c "  tensorboard --bind_all --logdir  /home/app/mava/logs/ & python examples/debugging/simple_spread/feedforward/decentralised/run_maddpg.py --base_dir /home/app/mava/logs/; "
```

Maybe my docker setup is wrong.

Here are the tensorlogs in case you need them [logs.zip](https://github.com/instadeepai/Mava/files/6974172/logs.zip) :smile:

**Comment by DriesSmit** [comment]
Thanks for the logs :+1:  I also tested it using Docker with a GPU and I could confirm that develop was training significantly faster than the mava-scaling branch. So nice catch:)  The GPU problem seems to have something to do with your local Docker setup. Maybe try running `docker run --rm --gpus all nvidia/cuda:11.0-base nvidia-smi` to see if it is a Mava problem or something with your Docker setup.

I made a few improvements to the mava-scaling branch and it seems to be training faster now. I did test it on my side and it seems to be much closer to develop's performance after the updates. If you have time, let me know if you also see improved performance using the mava-scaling branch on  [run_maddpg.py](https://github.com/instadeepai/Mava/blob/develop/examples/debugging/simple_spread/feedforward/decentralised/run_maddpg.py)? Thanks!

**Comment by mlanas** [comment]
Apparently I was missing the [nvidia-container-toolkit](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html), the GPU works now :)

I did some tests with this commit https://github.com/instadeepai/Mava/commit/dc9348de54db88a209b5e907c86f77f3dabc7c26 and it looks much better than the previous one, but it still has some performance loss. It does not reach the good score (35) for this environment , while the 0.1.0 version does. Is this the expected behavior? Not sure if that's related to the training implementation, but doesn't seem right. :thinking: 

![scaling_fix_runs](https://user-images.githubusercontent.com/56938299/129201435-442db93c-117f-4ba0-887f-7dd4594edf94.png)

**Comment by DriesSmit** [comment]
I am glad you got your GPU working. On my side this is what I get using the mava-scaling branch:
![Screenshot from 2021-08-12 14-28-38](https://user-images.githubusercontent.com/30599100/129207179-cd712ef0-0e06-44f3-92a5-295783d52ffa.png)

Did you pull the latest changes in the branch?

**Comment by mlanas** [comment]
Your results really look good :laughing: . I won't be able to test for the next days, but I'll do it as soon as I can :wink: thanks for the fix btw!

**Comment by DriesSmit** [comment]
That sounds good :smile: Thanks for pointing out the problem :+1: My code is running faster as a result of this fix as well. So thank you too!

**Comment by mlanas** [comment]
I does look much better!! I'm just not sure why I'm taking longer to get to 35?

![image](https://user-images.githubusercontent.com/56938299/129894628-6cf94e23-dfe4-4850-b1bc-dd63b8744fd9.png)

**Comment by DriesSmit** [comment]
You are looking at the MeanEpisodeReturn where I looked at the RawEpisodeReturn. So your results look good:) I am glad things are working better now :+1:

**Comment by mlanas** [comment]
Ah okay did not notice that, then looks like its fixed :ok_hand:

**Comment by DriesSmit** [comment]
Great :smile: You can then close the issue when you are ready.
