### ISSUE TITLE
How should I add a new environment

### ISSUE THREAD

**Issue by WYHbxer** [instadeepai/Mava#298]
I have built a multi-agent environment based on gym. Now I want to use it in Mava. How can I operate it?

**Comment by DriesSmit** [comment]
Hey @WYHbxer. Great question. If you look in the [debugging_utils](https://github.com/instadeepai/Mava/blob/develop/mava/utils/environments/debugging_utils.py#L53) you will see that this can be done in two steps. Firstly, you can initialise your environment as normal. Then you need to create a wrapper for your environment that conforms to Deepmind's `dm_env.Environment` standard. We also added 3 extra methods that can be seen in the [env_wrappers](https://github.com/instadeepai/Mava/blob/develop/mava/wrappers/env_wrappers.py). If all the agents take an action in the same step in your environment, the [PettingZooParallelEnvWrapper](https://github.com/instadeepai/Mava/blob/develop/mava/wrappers/pettingzoo.py#L266) might be a good reference point for you to work from. Let me know if this answered your question?

**Comment by WYHbxer** [comment]
Thank you.
I have completed the construction and encapsulation of the environment, but when I was testing the environment, I found new problems. When I run Mava development / tests / wrappers / wrapper_test.py  The error "cannot import name' node' from' flatland. envs. observations' always appears
My flatland version is 0.9.1. Of course, I also tested the installation of flatland versions 0.9.0 and 0.8.1, and there will still be this error

**Comment by DriesSmit** [comment]
@KaleabTessera @jcformanek have you ever encountered this problem before?

**Comment by WYHbxer** [comment]
This is my first attempt to use this test program.
Before that, I successfully ran 'simple_ spread.py'。 But when I run 'examples/petting_zoo/atari/pong/feedforward/decentralised/run_madqn.py', The following error occurred: '__ init__()  got an unexpected keyword argument 'importance_ sampling_ exponent'
I haven't made any changes to the code, so I wonder if I made a mistake when installing Mava, and what should I do.
Please, I hope to get your answer

**Comment by KaleabTessera** [comment]
@WYHbxer the `The error "cannot import name' node' from' flatland. envs. observations'` error happens because of the order that the libraries were installed in. We install flatland before other dependencies like this :https://github.com/instadeepai/Mava/blob/0a952cc124dcb5e9a00250ba7a6e8eab57ea25d2/Dockerfile#L43 Apologies for any inconvenience. 

@jcformanek Can you maybe assist with the `importance_ sampling_ exponent` error?

**Comment by WYHbxer** [comment]
Thank you.
I solved the problem by directly annotating this parameter.
Now that I have an encapsulated environment, how can I create a file and start training in this environment?

**Comment by DriesSmit** [comment]
You can simply copy one of the example files (e.g. [here](https://github.com/instadeepai/Mava/blob/develop/examples/debugging/simple_spread/feedforward/decentralised/run_maddpg.py)). 

Then just set the `environment_factory` equal to your wrapped environment.

**Comment by WYHbxer** [comment]
Thank you.
I packaged the environment as you said. When I started executing files for training, the following errors occurred
`[trainer/0] dtype = _assert_float_dtype(_get_dtype(dtype))
[trainer/0]
File " /home/ hongxiaopeng/miniconda3/envs/mava_wyh/lib/python3.7/site_packages/keras/initializers/initializers_v2.py" , line 942, in_assert_float_dtype
[trainer/0]raise valueError ( 'Expected floating point type. got %s. ' % dtype)
[trainer/0] ValueError: Expected floatingpoint type, got <dtype: 'int64 '>.`

I run the routine you gave me, and turn the loaded environment into mine.I don't know if there is a problem in any link. I hope to get your advice.

**Comment by DriesSmit** [comment]
Hello there. This error seems to have something to do with initialising your model. Where in Mava's code does this error occur? Can you maybe paste the entire error message? Thanks.

**Comment by KaleabTessera** [comment]
Hi @WYHbxer , this appears to be a similiar issue to https://github.com/instadeepai/Mava/issues/335 . The networks used for your example don't seem to support discrete observations. Please follow the suggestion in that issue and let us know if it solves your problem.
