### ISSUE TITLE
cannot import name '_PaddingFn' from 'acme.adders.reverb.episode'

### ISSUE THREAD

**Issue by KiloNovemberDelta** [instadeepai/Mava#311]
Hello everyone,

I'm using the develop branch, and installed Mava following this pip installation:
```
pip install --upgrade pip setuptools
pip install id-mava
pip install id-mava[reverb]
pip install id-mava[tf]
pip install id-mava[launchpad]
pip install id-mava[envs]
```

However, when I run this simple code https://github.com/instadeepai/Mava/blob/develop/examples/debugging/simple_spread/feedforward/centralised/run_mappo.py I get the following error:
```
Traceback (most recent call last):
  File "/home/jamy/git/Mava/examples/debugging/simple_spread/feedforward/centralised/run_mappo.py", line 27, in <module>
    from mava.systems.tf import mappo
  File "/home/jamy/git/Mava/mava/systems/tf/mappo/__init__.py", line 18, in <module>
    from mava.systems.tf.mappo.system import MAPPO
  File "/home/jamy/git/Mava/mava/systems/tf/mappo/system.py", line 35, in <module>
    from mava.systems.tf.mappo import builder, execution, training
  File "/home/jamy/git/Mava/mava/systems/tf/mappo/builder.py", line 31, in <module>
    from mava.adders import reverb as reverb_adders
  File "/home/jamy/git/Mava/mava/adders/reverb/__init__.py", line 27, in <module>
    from mava.adders.reverb.episode import ParallelEpisodeAdder
  File "/home/jamy/git/Mava/mava/adders/reverb/episode.py", line 32, in <module>
    from acme.adders.reverb.episode import EpisodeAdder, _PaddingFn
ImportError: cannot import name '_PaddingFn' from 'acme.adders.reverb.episode' (/home/jamy/git/Mava/venv/lib/python3.8/site-packages/acme/adders/reverb/episode.py)
Process finished with exit code 1
```
Here is the requirement file from pip freeze command:
[requirements.txt](https://github.com/instadeepai/Mava/files/7099907/requirements.txt)

However, running the code wasn't a problem few days ago. It looks to me something broke the code. Or is my installation wrong?

**Comment by KaleabTessera** [comment]
Hi @KiloNovemberDelta , can you try updating your version of acme like `pip install dm-acme --upgrade`. It should be version `0.2.2` like specified in our setup.py (https://github.com/instadeepai/Mava/blob/cbdbf6a90a3750428f29cc5e893ad67b54d6cee8/setup.py#L96).

**Comment by KiloNovemberDelta** [comment]
Indeed, it's working now, thank you!
