### ISSUE TITLE
Applying diffrentiable communication to my custom env

### ISSUE THREAD

**Issue by kiranikram** [instadeepai/Mava#312]
Hi, I'd like to apply your implementation of learnable communication to my custom env [env](https://github.com/kiranikram/HexaJungle) . I believe the first step is to create a wrapper similar to the pettingzoo example. What would be the next steps to integrate a communication channel between my agents?

**Comment by KevinEloff** [comment]
Hi, it would really depend on what sort of communication you'd like to implement. But yes, you'd first need a custom wrapper for your environment. If you're looking for simple differentiable communication something similar to DIAL [(Foerster 2016)](https://arxiv.org/abs/1605.06676), the easiest way to implement it is by having a custom executor and trainer. With this, its probably best to keep your communication separate to the environment itself and handle it with the executor entirely (although you could implement it with the environment through extras)

Alternatively you can use our own DIAL based implementations (see example [here](https://github.com/instadeepai/Mava/blob/develop/examples/debugging/simple_spread/recurrent/decentralised/run_madqn_with_coms.py)). In this example we initialise our system as using recurrent MADQN with communication:
```python
program = madqn.MADQN(
    ...
    trainer_fn=madqn.training.MADQNRecurrentCommTrainer,
    executor_fn=madqn.execution.MADQNRecurrentCommExecutor,
    ...
)
```
The current differentiable communication implementation uses a sort of shared differentiable recurrent state between each agent. We also apply a channel function before providing the message state as input to the agents in the next time-step (see [communication module](https://github.com/instadeepai/Mava/tree/develop/mava/components/tf/modules/communication)). Finally, a custom network architecture is also used (see [here](https://github.com/instadeepai/Mava/blob/develop/mava/components/tf/networks/communication.py)). This acts as a generic communicating agent allowing input and output of communication tensors.

Hope this helps.

**Comment by KaleabTessera** [comment]
Also here are the basic instructions on creating your own env [wrapper](https://github.com/instadeepai/Mava/blob/develop/mava/wrappers/README.md).

**Comment by kiranikram** [comment]
Thank you. I'll go ahead with creating a wrapper and then use your DIAL based implementations.

**Comment by kiranikram** [comment]
Hi would you recommend I use the [tests](https://github.com/instadeepai/Mava/blob/develop/tests/environment_loops/environment_loop_test.py) here to test the env wrapper before moving on ? Thank you!

**Comment by KaleabTessera** [comment]
Hi @kiranikram  :wave: 

So running the [wrapper tests](https://github.com/instadeepai/Mava/tree/develop/tests/wrappers) like this `pytest tests/wrappers/wrapper_test.py -s` would be a good step forward, but you would need to add your env wrapper to the tests by adding it here (https://github.com/instadeepai/Mava/blob/ec3c173c905136ba92369b93a953f55604b343ec/tests/wrappers/wrapper_test.py#L51) and by updating functions in the conftest.py (e.g. https://github.com/instadeepai/Mava/blob/7350cca643772da8dc474d5183552e8b8fdd2bf2/tests/conftest.py#L88 ). This maps a config or parameterized test to your wrapper. 

We have tried to make our wrapper tests general purpose, but some tests might be irrelevant for your environment. Here is an example on how to skip irrelevant tests: 
```
if env_spec.env_source == EnvSource.OpenSpiel:
    pytest.skip("Open Spiel does not use the .last() method")
```

Once you have done this / and want to continue, you need to create a function that returns your environment like this https://github.com/instadeepai/Mava/blob/3159ed45bce4936c8298085cad1bdefbac50160f/mava/utils/environments/debugging_utils.py#L29 and then find/copy a relevant example and update the environment factory to call the func that returns your environment https://github.com/instadeepai/Mava/blob/3159ed45bce4936c8298085cad1bdefbac50160f/examples/debugging/simple_spread/feedforward/decentralised/run_mad4pg.py#L52 

Please let me know if you have any other questions.
