### ISSUE TITLE
Questions about multiwalker

### ISSUE THREAD

**Issue by jkterry1** [instadeepai/Mava#314]
Hey, a quick question- how many timesteps did you train multiwalker for with MAD4PG a few months ago when you were able to learn it so effectively that the environment broke and you created an issue with us?

**Comment by jkterry1** [comment]
The code you referenced is here, but unless I'm loosing my mind I'm not seeing where you defined timesteps in it: https://github.com/instadeepai/Mava/blob/develop/examples/petting_zoo/sisl/multiwalker/feedforward/decentralised/run_mad4pg.py

Also this is the GitHub issue I was referring to by the way: https://github.com/PettingZoo-Team/PettingZoo/issues/376

**Comment by KaleabTessera** [comment]
Hi @jkterry1 :wave: 

It took ~1000000 (1e6) executor steps (logged as `evaluator/ExecutorSteps`) / ~1h to reach a return (logged as `evaluator/RawEpisodeReturn` or `evaluator/MeanEpisodeReturn`) of ~40. I think the prev PZ multiwalker env broke around then.

We used this config: 

Config | Param
-- | --
batch_size | 1024
critic_optimizer | Adam
critic_optimizer_lr | 0.0001
discount | 0.99
executor_variable_update_period | 1000
max_gradient_norm | None
policy_optimizer | Adam
policy_optimizer_lr | 0.0001
shared_weights | True
sigma | 0.3
target_averaging | False
target_update_period | 100


Relating to timesteps, each system has a `max_executor_steps` (https://github.com/instadeepai/Mava/blob/3159ed45bce4936c8298085cad1bdefbac50160f/mava/systems/tf/mad4pg/system.py#L75)  which limits how many steps/timesteps our executors (more on executors [here](https://github.com/instadeepai/Mava#systems-and-the-executor-trainer-paradigm))  run for. If this is none, we let the experiment run until it is manually cancelled. Not sure if this answers your question?

**Comment by jkterry1** [comment]
That answers most of it, thank you. One follow up question: is 100 million executor steps steps for each individual agent in th env or a step for all agents at once?

**Comment by KaleabTessera** [comment]
@jkterry1 It is a step for all agents at once (parallel) since our executors are a collection of agents.

**Comment by jkterry1** [comment]
Thanks a ton!

**Comment by jkterry1** [comment]
One additional question- what preprocessing did you do and why?

**Comment by jkterry1** [comment]
And do you know how much average total reward you were getting when multiwalker broke?
