### ISSUE TITLE
Mac installation

### ISSUE THREAD

**Issue by MarvEltun** [instadeepai/Mava#321]
The compatibility of libraries is problematic for Mac. Installation is not almost possible. It works in Windows based systems. 

OS: Mac OS Big Sur

**Comment by KaleabTessera** [comment]
Hi @MarvEltun , apologies for the inconvenience, but a lot of our dependencies like [reverb](https://github.com/deepmind/reverb/issues/11) don't support Mac natively.  However, following the [docker installation steps](https://github.com/instadeepai/Mava#docker-recommended) should work when using Mac (we have tested this on Mac systems).
