### ISSUE TITLE
Custom logging metrics

### ISSUE THREAD

**Issue by ricky-ma** [instadeepai/Mava#327]
How do I add custom logging metrics? I.e. reward and custom environment variables

**Comment by KaleabTessera** [comment]
Hi @ricky-ma , the easiest way to add custom logging metrics is to update the `DetailedPerAgentStatistics` class and update the running stats variable (https://github.com/instadeepai/Mava/blob/57ae3c8562e77b21e4cfa72b91fa65665f77aa04/mava/wrappers/environment_loop_wrappers.py#L238).  

To make this easier, in one of pull requests, we have added a check (https://github.com/instadeepai/Mava/blob/831ea52f292b231cfbbff86e57cfc8b3d3ceb39d/mava/wrappers/environment_loop_wrappers.py#L242) to read if your env has a `get_stats` function and if it does, we add the information to our logging metrics. Here is an example of a `get_stats` function (https://github.com/instadeepai/Mava/blob/831ea52f292b231cfbbff86e57cfc8b3d3ceb39d/mava/systems/tf/madqn/execution.py#L82). Once this PR is merged (hopefully end of this week or early next week), you only need to implement a `get_stats` method in your environment and our loops will handle the rest.

**Comment by ricky-ma** [comment]
Awesome, looking forward to this. Thanks!

**Comment by ricky-ma** [comment]
@KaleabTessera Hi there, any updates regarding this PR? No rush!

**Comment by KaleabTessera** [comment]
@ricky-ma Unfortunately the PR with these changes is still a WIP. You work directly off this branch - https://github.com/instadeepai/Mava/tree/feature/smac-env-upgrades . The custom logging metrics should work as mentioned above, we just have some other fixes in this branch before we can merge it in.

**Comment by ricky-ma** [comment]
@KaleabTessera Thanks, just tested with this branch and it seems like the get_stats() function isn't being called? I'm using a custom PettingZoo environment w/ MADQN. I've tried debugging here:
https://github.com/instadeepai/Mava/blob/feature/smac-env-upgrades/mava/wrappers/pettingzoo.py#L635
and here:
https://github.com/instadeepai/Mava/blob/831ea52f292b231cfbbff86e57cfc8b3d3ceb39d/mava/systems/tf/madqn/execution.py#L82
It seems like neither of these functions are being called. Any idea what's going on? Appreciate the help!

**Comment by KaleabTessera** [comment]
@ricky-ma Can you confirm that your MADQN has this line - https://github.com/instadeepai/Mava/blob/ae0cb9913bc2e7341f3188f6445ad4546c0826dc/mava/systems/tf/madqn/system.py#L520 .

Then here (https://github.com/instadeepai/Mava/blob/ae0cb9913bc2e7341f3188f6445ad4546c0826dc/mava/wrappers/environment_loop_wrappers.py#L147), `DetailedPerAgentStatistics` checks if your environment has a `get_stats()` method and if it does, it calls it and gets the dict returned and appends it to the running stats. 

If you are using a custom PZ environment, are you wrapping it with `PettingZooParallelEnvWrapper`? It should work either way, as long as the environment has a callable `get_stats` method.

**Comment by ricky-ma** [comment]
Ahh I see the problem. I've been trying to log stats each step, but the default is to write to the logger after each episode - got it working now. Thanks for your help!
