### ISSUE TITLE
What is decentralized MADDPG?

### ISSUE THREAD

**Issue by mlanas** [instadeepai/Mava#330]
Hi guys, I have a doubt about the MADDPG implementations. According to the paper, the main idea of MADDPG is a centralized training, where there is information sharing between agents a training time to reduce the variance. In Mava there is a "Decentralized Training" implementation of MADDPG, is this a DDPG implementation? Or is there any MADDPG feature in it?

**Comment by DriesSmit** [comment]
Hey @mlanas . The centralised MADDPG follows the paper yes. The decentralised MADDPG is actually just DDPG as you correctly stated.

**Comment by mlanas** [comment]
Hey @DriesSmit , thanks for the answer, now it's clear :)
