### ISSUE TITLE
Issue running quickstart notebook

### ISSUE THREAD

**Issue by vanpra** [instadeepai/Mava#331]
Hey everyone,

Thanks a lot for developing this library. I'm currently trying to run the quick start python notebook ([here](https://colab.research.google.com/github/instadeepai/Mava/blob/develop/examples/quickstart.ipynb)) but seem to be getting the following error on the third cell:
![DeepinScreenshot_select-area_20211119000929](https://user-images.githubusercontent.com/11397688/142517299-97afd0e6-a21f-4a50-9a58-aeb4b04301ed.png)

I also get the same error when trying to integrate mava into a project I'm working on locally as well. I think this might have to do with this issue https://github.com/deepmind/launchpad/issues/18, but I wanted to report the error here as well in case there is a different root cause. I also tried overriding the `tensorflow` dependency to use `2.7.0` as the issue suggests, but, although I no longer saw the error above, I encountered a `Segfault` which I assume is due to incompatibility with the newer version. 

I would appreciate any help to either resolve or workaround this issue.

**Comment by KaleabTessera** [comment]
Hi @vanpra :wave: , thanks for pointing this issue out! 

So we have a fix for this, it is just part of another branch that hasn't been merged in. 

In the meantime, can you create an new environment and then try `pip install git+https://github.com/instadeepai/Mava.git@feature/smac-env-upgrades` , this should sort out the `launchpad` issue. Please let me know if you still get an error.

**Comment by KaleabTessera** [comment]
Notebook is working now.
