### ISSUE TITLE
Render frames exception: Cannot connect to "None"

### ISSUE THREAD

**Issue by ricky-ma** [instadeepai/Mava#333]
Hi there, I'm trying to record training episodes for a custom PettingZoo environment. 

I have this in my Dockerfile:
```
RUN apt-get update -y && \
    apt-get install -y xvfb && \
    apt-get install -y python-opengl && \
    apt-get install -y ffmpeg && \
    apt-get install -y fontconfig
ENV DISPLAY=:0
RUN pip install pyglet```

As well as this command in my Makefile:
```Xvfb -screen 0 1024x768x24```

**Comment by KaleabTessera** [comment]
Hi @ricky-ma , so there is an extra bash script that needs to run on startup when recording in docker. The version on develop seems to be temporarily not working, can you try this from one of our branches and let us know if it works (i.e. `make run-record example=`)
https://github.com/instadeepai/Mava/blob/335353ccf53b9db0d9ac458c69a9fa7c0088ab87/Makefile#L55 

Your container needs to build with record set true as follows - `make build version=[] record=true`. This branch should be merged into dev soon.

**Comment by KaleabTessera** [comment]
Hi @ricky-ma , were you able to use the `run-record` command? This has been merged into our dev branch for now.
