### ISSUE TITLE
Issues with Windows Installation

### ISSUE THREAD

**Issue by AsadJeewa** [instadeepai/Mava#339]
I am having dependancy issues when instaling mava on Windows with a venv. 

Firstly, when I run `pip install id-mava[launchpad]`

Firstly, 

> ERROR: Could not find a version that satisfies the requirement dm-reverb~=0.4.0 (from id-mava[reverb]) (from versions: none)
> ERROR: No matching distribution found for dm-reverb~=0.4.0

Secondly, when I run `pip install id-mava[reverb]`

> ERROR: Could not find a version that satisfies the requirement dm-launchpad-nightly (from id-mava[launchpad]) (from versions: none)
> ERROR: No matching distribution found for dm-launchpad-nightly

I plan to use Docker but wanted to get moving quickly with a venv for now.

**Comment by AsadJeewa** [comment]
I did a fresh install and I still have dependency issues 

> ERROR: Cannot install id-mava[reverb]==0.0.9 and id-mava[reverb]==0.1.0 because these package versions have conflicting dependencies.

> ERROR: Cannot install id-mava[launchpad]==0.0.9 and id-mava[launchpad]==0.1.0 because these package versions have conflicting dependencies.

**Comment by KaleabTessera** [comment]
Hi @AsadJeewa , unfortunately reverb doesn't natively support windows (https://github.com/deepmind/reverb#installation) and hence I recommend following the docker instructions.
