### ISSUE TITLE
[BUG] Optimizers for critic and policy both backpropagating on observation network

### ISSUE THREAD

**Issue by EdanToledo** [instadeepai/Mava#364]
**Describe the bug**
Both optimizers train the observation network separately which can caused the representation learnt to be unstable. Happens in MAD4PG.

**Expected behavior**
only one optimizer should work on the observation network or there should be a single optimizer.

**Comment by EdanToledo** [comment]
@arnupretorius - Adding the option for a single optimizer is easy and I will do it now but from a design standpoint which optimizer should optimize the observation network in the double optimizer case because either way if the critic and policy both use it, it will potentially cause instability.

**Comment by DriesSmit** [comment]
Closing all TF issues as we are depreciating our TF systems.
