### ISSUE TITLE
[FEATURE] Investigate Using TrajectoryDataset for Recurrent Systems

### ISSUE THREAD

**Issue by KaleabTessera** [instadeepai/Mava#397]
### Feature
Investigating using `reverb.TrajectoryDataset` for all recurrent systems.

### Proposal
Change `make_dataset_iterator` to use `reverb.TrajectoryDataset`  since it appears that TrajectoryDataset works better (faster trainer speed) when using the SequenceAdder.

### Definition of done
All recurrent systems use `reverb.TrajectoryDataset` , with a full benchmark of performance results. 

### Mandatory checklist before making a PR
* [ ] The success criteria laid down in “Definition of done” are met.
* [ ] Code is documented - docstrings for methods and classes, static types for arguments.
* [ ] Code is tested - unit, integration and/or functional tests are added.
* [ ] Documentation is updated - README, CONTRIBUTING, or other documentation.
* [ ] All functional tests are green.
* [ ] Link experiment/benchmarking after implementation (optional).

**Comment by DriesSmit** [comment]
Closing all TF issues as we are depreciating our TF systems.
