### ISSUE TITLE
[FEATURE] Auto push docker image when PR has an updated commit 

### ISSUE THREAD

**Issue by KaleabTessera** [instadeepai/Mava#408]
### Please describe the purpose of the feature. Is it related to a problem?
Currently docker images are pushed when you tag PR with the `benchmark` tag. If you push more commits to an existing PR, you need to untag and then tag `benchmark` again. 

### Describe the solution you'd like
This should be done automatically by the github action (you shouldn't have to tag and untag).

### Describe alternatives you've considered
-

### How do we know when implementation of this feature is complete?
Checklist:
-  PR with the tag `benchmark` auto push new images when they have new commits.

**Comment by DriesSmit** [comment]
Closing all TF issues as we are depreciating our TF systems.
