### ISSUE TITLE
[BUG] Inconsistent Observation Networks

### ISSUE THREAD

**Issue by KaleabTessera** [instadeepai/Mava#419]
### Describe the bug
We need to standardize how we handle observation networks. 

We have the following options:
1. Have both critic and policy networks update the obs network vars. This would mean that the critic loss and policy loss would compete when updating the observation networks. This could hurt performance. 
2. Have either policy or critic loss update obs networks - need to use `stop_gradients` carefully here.  

Current PPO PR uses option 2 (only critic loss to update the obs variables  - if `self._use_single_optimizer=False` https://github.com/instadeepai/Mava/blob/cc86102881e5b2799ba78e22877b284a201ce875/mava/systems/tf/mappo/training.py#L520 , while ddpg and d4pg use option 1 (https://github.com/instadeepai/Mava/blob/e00724a84001b8ca9f00d3230d998c786d9d7928/mava/systems/tf/maddpg/training.py#L461). 

### To Reproduce
-

### Expected behavior
Consistent, correct handling of obs network vars. 

### Context (Environment)
-

### Proposal for a fix
Consistent, correct handling of obs network vars.  Possible use utility function. 

### Definition of done
When all systems handle obs network vars the same way. 

### Mandatory checklist before making a PR
* [ ] The success criteria laid down in “Definition of done” are met.
* [ ] Code is documented - docstrings for methods and classes, static types for arguments.
* [ ] Code is tested - unit, integration and/or functional tests are added.
* [ ] Documentation is updated - README, CONTRIBUTING, or other documentation.
* [ ] All functional tests are green.
* [ ] Link experiment/benchmarking after implementation (optional).

**Comment by DriesSmit** [comment]
Closing all TF issues as we are depreciating our TF systems.
