### ISSUE TITLE
[BUG] get_agent_type assumes naming convention that is not consistent across all of our environments

### ISSUE THREAD

**Issue by AsadJeewa** [instadeepai/Mava#434]
### Describe the bug
https://github.com/instadeepai/Mava/blob/develop/mava/specs.py#L68 assumes that agents from all environments are named with the convention `type_identifier` and hence using `split` to extract type. This is in some environments such as OpenSpiel/Tic Tac Toe since agents are named player_0 and player_1

### To Reproduce
1.Run examples/tf/openspiel/tic_tac_toe/feedforward/decentralised/run_madqn.py
2.Log output of get_agents_types()

### Expected behavior
Player_0 and Players_1 should be regarded as separate types and not a single agent type of name Player

### Context (Environment)
 - Latest Mava as of 24-02-22
 
### Possible Solution
Flag to specify environment type which will be used to set agent type

**Comment by DriesSmit** [comment]
Closing all TF issues as we are depreciating our TF systems.
