### ISSUE TITLE
[BUG] Net Spec Keys is overwritten in MADDPG

### ISSUE THREAD

**Issue by EdanToledo** [instadeepai/Mava#474]
### Describe the bug
In the MADDPG system, regardless of the net spec keys given to the network_factory (i.e create_default_networks), the system overwrites these values. This causes issues when trying to give different networks to different agents. This issue occurs on line 318 and 449.

### To Reproduce
1. Input any non-standard net_spec_keys to the create default network method 
2. Witness that the inputted value is not carried over

### Expected behavior
The given net_spec_keys should be used otherwise the default values should be constructed.

### Context (Environment)
 - Latest Mava 
 - Ubuntu Linux

### Additional context
Haven't inspected other classes, might only be present in MADDPG.

### Possible Solution
Somehow check for given value - not sure if this is possible. Maybe make net_spe_keys a parameter to the system instead of the network factory.

**Comment by DriesSmit** [comment]
Closing all TF issues as we are depreciating our TF systems.
