### ISSUE TITLE
[INVESTIGATION] MADDPG/MAD4PG are slower than MAPPO in certain instances (pixel-based environments?)

### ISSUE THREAD

**Issue by AsadJeewa** [instadeepai/Mava#482]
### What do you want to investigate?
MADDPG/ MAD4PG are both significantly slower than MAPPO in certain instances. 

1. Run MADDPG on Coop pong/ PCB Grid for n steps with the same network size
2. Run MAAPO on Coop pong/ PCB Grid for n steps with the same network size
3. Observe that MAPPO takes significantly shorter to run the same number of executor steps 
[PPO](https://app.neptune.ai/o/InstaDeep/org/Mava/experiments?compare=KwRgzMA0IExA&split=cmp&dash=charts&viewId=standard-view&query=((%60sys%2Ftags%60%3AstringSet%20CONTAINS%20%22b-match-pcbgrid-mappo-critic-medium-2022-04-12_08-58-17%22)%20OR%20(%60sys%2Ftags%60%3AstringSet%20CONTAINS%20%22b-match-pcbgrid-mappo-critic-medium-2022-04-12_07-21-19%22)%20OR%20(%60sys%2Ftags%60%3AstringSet%20CONTAINS%20%22b-test-pcbgrid-mappo-critic-medium-2022-04-11_09-32-41%22))&sortBy=%5B%22sys%2Fcreation_time%22%5D&sortFieldType=%5B%22datetime%22%5D&sortFieldAggregationMode=%5B%22auto%22%5D&sortDirection=%5B%22descending%22%5D&suggestionsEnabled=true&lbViewUnpacked=true) ~2:45 hours for 2e6 executor steps
[D4PG](https://app.neptune.ai/o/InstaDeep/org/Mava/experiments?compare=KwRgDGA0KckMzUgJiA&split=cmp&dash=charts&viewId=standard-view&query=((%60sys%2Ftags%60%3AstringSet%20CONTAINS%20%22b-*pcbgrid-mad4pg-critic-easy-2022-04-08_13-44-10%22)%20OR%20(%60sys%2Ftags%60%3AstringSet%20CONTAINS%20%22b-*pcbgrid-mad4pg-both-easy-2022-04-07_16-59-06%22)%20OR%20(%60sys%2Ftags%60%3AstringSet%20CONTAINS%20%22b-final-pcbgrid-mad4pg-both-easy-2022-04-11_09-13-22%22)%20OR%20(%60sys%2Ftags%60%3AstringSet%20CONTAINS%20%22b-final-pcbgrid-mad4pg-critic-easy-2022-04-11_09-02-18%22)%20OR%20(%60sys%2Ftags%60%3AstringSet%20CONTAINS%20%22b-final-pcbgrid-mad4pg-critic-easy-2022-04-11_09-12-48%22))&sortBy=%5B%22sys%2Fcreation_time%22%5D&sortFieldType=%5B%22datetime%22%5D&sortFieldAggregationMode=%5B%22auto%22%5D&sortDirection=%5B%22descending%22%5D&suggestionsEnabled=true&lbViewUnpacked=true) ~36 hours for 2e6 executor steps

NB: This could be in pixel-based environments or due to alternate environment characterisitcs. It could also be a launchpad issue since significantly more evaluator steps are being run for MADDPG when not setting an interval. 

### Definition of done
Baseline experiments highlighting specific characteristics/ instances that show a clear difference in performance
Bug fixed (in system or env) if one exists

**Comment by DriesSmit** [comment]
Closing all TF issues as we are depreciating our TF systems.
