### ISSUE TITLE
[BUG] Inconsistent Logging of Jax Systems

### ISSUE THREAD

**Issue by KaleabTessera** [instadeepai/Mava#492]
### Describe the bug
Jax system logs look different compared to tf system logs. 

### To Reproduce
1. Run jax example.
2. Run tf example.
3. Compare tensorboard logs. 

### Expected behavior
Same logs. 

### Context (Environment)
-

### Additional context
-

### Possible Solution
Use the same env stats wrapper.

**Comment by DriesSmit** [comment]
This issue has been resolved.
