### ISSUE TITLE
[TEST] Jax Checkpointers

### ISSUE THREAD

**Issue by mmorris44** [instadeepai/Mava#539]
### What do you want to test?
Jax checkpointer components. Needs to wait until checkpointers are actually created.

### Outline of test structure
* Unit tests
* Test components and hooks

### Definition of done
Passing checks, cover all hooks, edge cases considered

### Mandatory checklist before making a PR
* [ ] The success criteria laid down in “Definition of done” are met.
* [ ] Test code is documented - docstrings for methods and classes, static types for arguments.
* [ ] Documentation is updated - README, CONTRIBUTING, or other documentation.

**Comment by RuanJohn** [comment]
We do not have checkpoint components yet. We can open an issue for testing the component again in the future when it is implemented.
