### ISSUE TITLE
Usage documentation is incorrect

### ISSUE THREAD

**Issue by cool-RR** [instadeepai/Mava#572]
I'm a first-time Mava user. I'm trying to figure out how to use it. In the [docs homepage](https://id-mava.readthedocs.io/en/latest/#system-implementations) there's a "Usage" section with a code snippet. I'm trying to run this code snippet, but it fails because it's trying to import a local module called `helpers`, which isn't provided.

**Comment by jdtotow** [comment]
I've managed to run some example, located at `https://github.com/instadeepai/Mava/tree/develop/examples/tf/debugging/simple_spread/feedforward/centralised`.

**Comment by cool-RR** [comment]
@jdtotow : Thank you, can you share which of the 3 files worked for you?

**Comment by jdtotow** [comment]
I tested only run_mddpg.py and works successfully. However i'm having difficulty to [retrieve the "executor" ](https://stackoverflow.com/questions/72594771/accessing-executor-methods-after-program-launch)for interacting with the environment
