### ISSUE TITLE
Accessing executor methods after program launch

### ISSUE THREAD

**Issue by jdtotow** [instadeepai/Mava#583]
I studying the project for integrating with a maddpg based system, Actually i'm trying to access executor methods most importantly "select_actions" methods for collecting actions from agents. From the maddpg example provided, i'm retrieving the executor node from program object (CourierNode)

```
program = maddpg.MADDPG(...).build()
(executor_node,) = program.groups["executor"]
```
Then i'm constructing a client to access the parallelenvloop method

`parallel_env_loop = executor_node.create_handle().dereference()`

unfortunately i cannot access any MADDPGFeedForwardExecutor class methods (select_actions, observer, update) from parallel_env_loop._executor

`AttributeError: 'function' object has no attribute 'select_actions'`
any idea ?? thanks

**Comment by siddarthsingh1** [comment]
I am not sure about gRPC as I have not made use of it but, could you explain why you need to access the executor functions during runtime so I can better understand what this is being used to do?

**Comment by jdtotow** [comment]
Actually, i'm allocating resource in real-time to a cloud application where the state representation of each application component is the combination of [memory, cores, number_of_instance, some_metrics .. ]. I have to ingest this array to the RL engine (observe_first, observe) then collect the action recommended by the RL engine (select_actions). The environment will compute the performance of the cloud application using the state for assigning a reward. That's the scenario

**Comment by siddarthsingh1** [comment]
That's a very interesting use case @jdtotow . The only thing I would be worried about is if there are synchronization issues from the reverb functions. If you're finding that it work at the moment then it should be okay.
