### ISSUE TITLE
QMix Evaluator and Executor Episodes

### ISSUE THREAD

**Issue by dewet99** [instadeepai/Mava#691]
Hi there,

I'm using QMix with a custom environment, and training seems to occur, i.e the value losses are updated, but the Evaluator steps and episodes, as well as the Executor steps and episodes remain at 0. The Trainer steps are updated, though. I'm not quite sure where to start looking for the source of this problem; I've compared my wrapper to the implementation of the SMAC wrapper, but the SMAC example updates the mentioned values whereas my doesn't. Any pointers as to where I should start looking for the source of this problem?

**Comment by DriesSmit** [comment]
Hey there,

Appologies if we take long to reply at the moment. Most of us are at the Deep Learning Indaba this week. Does your environment wrapper work with VDN? @jcformanek you worked with QMIX. Have you seen this problem before?

**Comment by jcformanek** [comment]
hi there, thanks for reaching out. I am very please to here that you are trying our implementation of QMIX.

It sounds like the Executor nodes are either crashing or hanging.

There could be many reasons that the Executor is crashing. Ideally you would like to track down the error message in the logs somewhere. To do this it could help to set `terminal="gnome-terminal"` in

```lp.launch(
        program,
        lp.LaunchType.LOCAL_MULTI_PROCESSING,
        terminal="current_terminal",
        local_resources=local_resources,
    )```

This will display each of the processes logs in a different terminal. I find this helpful for finding any errors in a specific process. Unfortunately, I dont think this will work if you are using Docker.

If there are no error logs in the Executor processes, then the process is hanging/stuck. This is likely because of Reverb. If you configure the `sample_to_insert` ratio wrong then the executors could get stuck. 

Please send me the configuration of the Value Decomposition System that you used. Is it identical to the examples such as `examples/tf/smac/recurrent/centralised/run_qmix.py`

**Comment by dewet99** [comment]
Hi there.
Thank you for the response.

My configuration for the system is identical to the one you mentioned, other than the following:

- The flags were changed for use with my environment
- I made a custom `make_environment` function to be able to support my environment.

I should note, however, that I made some modifications to the QMIX algorithm to be able to use it with my environment, which has a MultiDiscrete action space. I essentially modified the networks to support the shape of my action space.

With regards to your feedback:
I've set the terminal to `terminal="gnome-terminal"`, but both the executor and evaluator terminals have no output other than the initial info consisting of the following:

executor/0:
the brain called portalPOCA?team=0 is just what the behaviour is called inside the Unity environment, I forgot to change it to portalQMIX after testing my agents with Unity's built-in POCA algorithm.
If I understand correctly, only the trainer should use the GPU which is why the executor and evaluator have the CUDA_ERROR_NO_DEVICE
```
bash: /home/hebrect/miniconda3/lib/libtinfo.so.6: no version information available (required by bash)
2022-08-23 09:55:38.818739: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
I0823 09:55:40.528857 140162258982720 node.py:62] Reverb client connecting to: localhost:24052
2022-08-23 09:55:40.565796: W tensorflow/python/util/util.cc:368] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
E0823 09:55:40.598704554 3025265 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies
[INFO] Connected to Unity environment with package version 2.0.1 and communication version 1.5.0
I0823 09:55:43.627505 140162258982720 environment.py:113] Connected to Unity environment with package version 2.0.1 and communication version 1.5.0
[INFO] Connected new brain: portalPOCA?team=0
I0823 09:55:44.406643 140162258982720 environment.py:297] Connected new brain: portalPOCA?team=0

```
evaluator/0:

```
bash: /home/hebrect/miniconda3/lib/libtinfo.so.6: no version information available (required by bash)
2022-08-23 09:55:38.612984: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2022-08-23 09:55:40.302154: W tensorflow/python/util/util.cc:368] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
E0823 09:55:40.330745990 3025239 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies
[INFO] Connected to Unity environment with package version 2.0.1 and communication version 1.5.0
I0823 09:55:42.959081 140506957276992 environment.py:113] Connected to Unity environment with package version 2.0.1 and communication version 1.5.0
[INFO] Connected new brain: portalPOCA?team=0
I0823 09:55:43.728296 140506957276992 environment.py:297] Connected new brain: portalPOCA?team=0



```
Finally, there's also an error which I haven't noticed before, in the terminal where I run the file from:
`b"Failed to register: Unable to acquire bus name 'launchpad.locallaunch.caccaicdajbicd'\n"`

Any insight into where I might start looking for my problem would be appreciated.

**Comment by DriesSmit** [comment]
Hey there,

You can try running your new QMIX system on the discrete debugging environment. You can still use your multi-discrete setup, but set it to one discrete output. This is just to check that the new QMIX algorithm works in our environment. If this works, then the problem probably lies with the environment wrapper.
