### ISSUE TITLE
[INVESTIGATION] PettingZoo Environments Wrappers

### ISSUE THREAD

**Issue by davidedomini** [instadeepai/Mava#705]
Are there any examples of how to wrap and use a pettingzoo environment in MAVA?

**Comment by DriesSmit** [comment]
Hey there. Thanks for reaching out.

Yes, in Mava we support multi-agent extensions of PettingZoo environments. See this [example](https://github.com/instadeepai/Mava/blob/develop/examples/tf/sisl/multiwalker/feedforward/decentralised/run_mappo.py). You can find the PettingZoo wrapper [here](https://github.com/instadeepai/Mava/blob/develop/mava/wrappers/pettingzoo.py).
