### ISSUE TITLE
[BUG] PettingZoo MPE environments action not in action space

### ISSUE THREAD

**Issue by RuanJohn** [instadeepai/Mava#745]
### Describe the bug
When running the `simple_spread_v2`, `simple_reference_v2` and `simple_speaker_listener_v3` PettingZoo `MPE`
environments the following error is raised:
```
AssertionError: action is not in action space
```
even though the actions that were taken are within the action space bounds given in the PettingZoo documentation [here](https://www.pettingzoo.ml/mpe/simple_spread), [here](https://www.pettingzoo.ml/mpe/simple_reference) and [here](https://www.pettingzoo.ml/mpe/simple_speaker_listener).  

### To Reproduce
1. Run any of the PettingZoo examples mentioned above

### Expected behavior
The action space error mentioned abobe will be raised. 

### Context (Environment)
 - A clean conda environment with Mava installed directly from the develop branch using `pip install -e .[jax,reverb,pz]`

### Possible Solution
It could be that Jax device arrays are not able to be passed to the environment?

**Comment by saiyuhang123** [comment]
I encountered this problem. My solution was to put the agent's name and action in a dict like this: Initialized Dictionary: {'name': 'John', 'age': 25, 'city': 'New York'}
