### ISSUE TITLE
[MAINTAIN] Test IPPO folder

### ISSUE THREAD

**Issue by DriesSmit** [instadeepai/Mava#761]
Currently, we do not have tests for files in the IPPO folder. This includes the IPPO networks. It might be worthwhile including tests for some of these files.

**Comment by OmaymaMahjoub** [comment]
@DriesSmit most of the lines are covered in the integration test of IPPO do you think it is important to make unit tests?
See the coverage [here](https://app.codecov.io/gh/instadeepai/Mava/tree/develop/mava/systems/ippo).
