### ISSUE TITLE
[FEATURE] Load trained weights and run agents 

### ISSUE THREAD

**Issue by MoMe36** [instadeepai/Mava#821]
### Please describe the purpose of the feature. Is it related to a problem?
In order to easily evaluate agents in multiple settings, it would be optimal to have a clear way to load trained weights and agents and run them in selected environments, similarly to stable_baseline load and evaluate setting. Currently, and to the best of my knowledge, the quickstart notebook and most examples available present approaches to construct system and launch them but not how to load trained agents. 

### Describe the solution you'd like
A clear way / function to load network to run trained agents

### Describe alternatives you've considered
Updating the system launch to restart from a given checkpoint and not go through weights updates [as in this issue](https://github.com/instadeepai/Mava/issues/289), but it's not clear how to do that

### How do we know when implementation of this feature is complete?
Checklist:
- [ One liner to load agents?  ]

### Additional context
As mentionned, I've seen  [this issue](https://github.com/instadeepai/Mava/issues/289) but it's not exactly clear how to get to the end result. Maybe just an update in documentation would suffice ? ((: 
Thanks a lot !

**Comment by KaleabTessera** [comment]
@OmaymaMahjoub @DriesSmit Can you provide more info on how to do this?

**Comment by OmaymaMahjoub** [comment]
Hello @MoMe36, thank you for the feature request!

In the latest version, Mava supports checkpointing and the ability to restore trained networks. To restore the networks, `experiment_path` must point to a 'checkpoints' folder, generated from a previous run. For more details, see this [example](https://github.com/instadeepai/Mava/blob/develop/examples/debugging/simple_spread/feedforward/decentralised/run_ippo_restore_checkpoint.py). A relevant parameter for you might be the `checkpoint_minute_interval` parameter, which controls the interval (minutes) between checkpointing. 

Moreover, I would suggest that you look at this feature  #744. We are currently implementing it (#814) and it will be available soon. This feature allows you to store and restore the network that performed the best over the course of training.

Once we merge the PR (#814), we will create some documentation explaining how it works :slightly_smiling_face: .

**Comment by MoMe36** [comment]
Awesome ! Thanks a lot ((: I'll test this approach this week-end and reopen the issue if necessary.
