### ISSUE TITLE
[FEATURE] Update PettingZoo version, add Gymnasium support

### ISSUE THREAD

**Issue by elliottower** [instadeepai/Mava#901]
### Please describe the purpose of the feature. Is it related to a problem?
This library uses an old version of PettingZoo (from march 2022), it would be great to be able to use current environments which have been updated with many bugfixes. This would require supporting Gymnasium as well as Gym, but that is not too difficult to do, and I would be happy to help if need be.

### Describe the solution you'd like

Update to PettingZoo 1.23.1, and add support for Gymnasium 1.28.1 (required for PettingZoo support)

### How do we know when implementation of this feature is complete?
Checklist:
- [ ]
- [ ]

### Additional context

[Gymnasium](https://github.com/Farama-Foundation/Gymnasium) is the maintained version of openai gym, which has had many bugfixes and improvements over the years. For reference, most other RL training libraries have added Gymnasium support and updated to new PettingZoo versions ([RLlib](https://github.com/ray-project/ray/tree/master/rllib), [Tianshou](https://github.com/thu-ml/tianshou), [stable-baselines3](https://github.com/DLR-RM/stable-baselines3/blob/e5deeed16efb57c34ccdcb14692439154d970527/docs/guide/install.rst#bleeding-edge-version), [CleanRL](https://github.com/vwxyzjn/cleanrl)).  

For information about upgrading and compatibility, see [migration guide](https://gymnasium.farama.org/content/migration-guide/) and [gym compatibility](https://gymnasium.farama.org/content/gym_compatibility/). The main difference is the API has switched to returning `truncated` and `terminated`, rather than `done`, in order to give more information and mitigate edge case issues.

Both Gymnasium and PettingZoo are maintained by the Farama Foundation, for more information see [https://farama.org/](https://farama.org/) or read our [announcement blog post](https://farama.org/Announcing-The-Farama-Foundation).

**Comment by sash-a** [comment]
Hi Elliot, thanks so much for reaching out—we appreciate it! We're moving Mava towards the JAX ecosystem and will only be supporting JAX based environments for the foreseeable future. Accordingly, we are now using Jumanji's environments and no longer using PettingZoo or Gym. 

Appreciate the issue and all the work you do in the RL community :smile:

**Comment by elliottower** [comment]
No worries, good to know about those environments I’ve not heard of them. FWIW Gymnasium is in the process of adding all their envs in Jax (next few months, by 1.0 release which is almost finished) and somebody at Farama is working on PettingZoo Jax envs, so maybe I can bump this and update you when these things are implemented and you could look into compatibility. Would definitely like to ensure ecosystems are compatible and such.
