### ISSUE TITLE
Upgrade to python 3.11

### ISSUE THREAD

**Issue by sash-a** [instadeepai/Mava#941]
### Please describe what needs to be maintained?
Upgrade python version, we are on 3.9, which is almost 3 years old at this point. 

Big reason for this is the discussion in #940 about having generic named tuples, which isn't possible in 3.9 or 3.10. But 3.11 brings other benefits also.

I have tested this locally and it worked out of the box.

**Comment by sash-a** [comment]
Solution we found in #940 was `from typing_extensions import NamedTuple`. Solves the immediate issue, although upgrading to 3.11 would still be nice, just not as urgent

**Comment by sash-a** [comment]
I have tested python 3.12 and it seems to work without issue, we should drop support for 3.9  (and possibly 3.10 also) soon as it is nearing end of life.

**Comment by liamclarkza** [comment]
I think this is a good idea - it would be nice to have language support for pattern matching too!

**Comment by WiemKhlifi** [comment]
Maybe along with this upgrade the pre-commit #1036 or move to ruff as suggested here #1002
