### ISSUE TITLE
[MAINTAIN] Drop dictionary config syntax for default `Hydra` config syntax

### ISSUE THREAD

**Issue by RuanJohn** [instadeepai/Mava#949]
### Please describe what needs to be maintained?
At the moment, Mava systems expect configs to be dictionaries but this is quite cumbersome as it leads to something like the following: 
```python
critic_optim = optax.chain(
        optax.clip_by_global_norm(config["system"]["max_grad_norm"]),
        optax.adam(config["system"]["critic_lr"], eps=1e-5),
    )
```
We should update this to use the default `Hydra` syntax which will make the above code look like this: 
```python 
critic_optim = optax.chain(
        optax.clip_by_global_norm(config.system.max_grad_norm),
        optax.adam(config.system.critic_lr, eps=1e-5),
    )
```
### Describe the outcome you'd like
We should use the default `Hydra` syntax.

**Comment by sash-a** [comment]
To add to this it would be nice to have a [dataclass that hydra can read the config into](https://hydra.cc/docs/tutorials/structured_config/config_groups/) so that we have some type hints when we do `config.xyz`
